site_name: Adaptable code
nav:
  - Home: index.md
  - Look at this: 0-look-at-this.md
  - First separation: 1-first-separation.md
  - Second separation: 2-separate-interfaces-subject.md
  - Complete separation: 3-separate-interfaces-functionality.md
  - Separate implementation: 4-large-clients.md
  - "Testing: Mocks vs test doubles": 10-mocks-vs-test-doubles.md
  - "Testing: Support mutability in test doubles": 11-mutability-doubles.md


theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
