site_name: Abstractions
nav:
  - Home: 0-index.md
  - Look at this: 0-look-at-this.md
  - First separation: 1-first-separation.md
  - Second separation: 2-separate-interfaces-subject.md
  - Complete separation: 3-separate-interfaces-functionality.md
  - Seperate implementation: 4-large-clients.md
  - Use in testing: 10-mocks-vs-test-doubles.md
  - 11: 11-mutability-doubles.md


theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
