site_name: Adaptable code
site_dir: build
nav:
  - Home: index.md
  - Look at this: 0-look-at-this.md
  - First separation: 1-first-separation.md
  - Second separation: 2-separate-interfaces-subject.md
  - Complete separation: 3-separate-interfaces-functionality.md
  - Separate implementation: 4-large-clients.md
  - "Testing":
      - "Mocks vs Fakes": testing/mocks-vs-fakes.md
      - "Fake: In Memory": testing/fakes-in-memory.md
      - "Fake: Database" : testing/fakes-database.md
      - "Fake: Support mutability": testing/mutability-fakes.md
  - "Considerations":
    - "When to introduce": considerations/when-introduce.md
    - "When to split up": considerations/when-split.md
    - "But I can't see": considerations/cant-see-implementation.md
  - "Conclusion": 13-outro.md



theme:
  name: readthedocs
  navigation_depth: 1
  highlightjs: true
  hljs_languages:
    - php
